[project]
python = "^3.13"
name = "e-referrals-service-patient-care-api"
version = "0.0.1-alpha"
description = "TODO"
authors = [
    #TODO add authors
]
readme = 'README.md'
license = "MIT"
repository = "https://github.com/NHSDigital/e-referrals-service-patient-care-api"
keywords = ["healthcare", "uk", "nhs"] #TODO add additional keywords
dynamic = ["dependencies", "requires-python"]


[tool.poetry]
package-mode = false


[tool.poetry.dependencies]
python = "^3.13"
pyyaml = "^6.0"
docopt = "^0.6.2"
jsonpath-rw = "^1.4.0"
semver = "^3.0.4"
gitpython = "^3.1.58"
lxml = "^6.1.1"
xmlformatter = "^0.2.9"
pytest-check = "^2.9.1"
requests = "^2.34.2"
openapi-core = "^0.22.0"
pytest-nhsd-apim = "^6.0.14"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.3.0"
black = "^26.5"
pip-licenses = "^5.5.0"
jinja2 = "^3.1.6"
pytest = "^9.1.1"
coverage = "^7.15"
aiohttp = "^3.14.3"
pytest-asyncio = "^1.4.0"
pytest-nhsd-apim = "^6.0.14"

[tool.poetry.scripts]
