# This is an OpenAPI Specification (https://swagger.io/specification/)
# for e-referrals-service-patient-care-api owned by NHS Digital (https://digital.nhs.uk/)
openapi: '3.0.0'
info:
  title: 'e-referrals-service-patient-care-api'
  version: 'Computed and injected at build time by `scripts/set_version.py`'
  description: |
    ## Overview
    Add a fully fledged description here with markdown syntax.
  contact:
    name: 'e-referrals-service-patient-care-api API Support'
    url: 'https://digital.nhs.uk/developer/help-and-support'
    email: api.management@nhs.net
servers:
  - url: 'https://sandbox.api.service.nhs.uk/e-referrals-service-patient-care-api'
    description: Sandbox environment.
  - url: 'https://int.api.service.nhs.uk/e-referrals-service-patient-care-api'
    description: Integration test environment.
  - url: 'https://api.service.nhs.uk/e-referrals-service-patient-care-api'
    description: Production environment.
paths:
  /FHIR/R4/ServiceRequest:
    get:
      parameters: 
        - $ref: 'components/schemas/queryParameters/Patient.yaml'
        - $ref: 'components/schemas/queryParameters/Category.yaml'
        - $ref: 'components/schemas/queryParameters/RevInclude.yaml'
        - $ref: 'components/schemas/headers/request/CorrelationID.yaml'
      summary: Retrieve Service Requests
      description: |
        ## Overview
        
        Use this endpoint to retrieve active referrals for a patient.  You can test the following scenarios in our sandbox environment:

        | Scenario                                    | Request Query Parameters                                                                                                  | Response                                                                |
        | ------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------| ----------------------------------------------------------------------- |
        | Service requests with Appointment and Task  | `patient:identifier`=`9912003888`, `category`=`3457005`, `_revinclude`=`Appointment:based-on`, `_revinclude`=`Task:focus` | Illustrates a Service request with 'Appointment' or 'Task' linked    |
        | Empty service request search response       | `patient:identifier`=`1000000001`, `category`=`3457005`, `_revinclude`=`Appointment:based-on`, `_revinclude`=`Task:focus` | Illustrates how a 'no service request' response appears.                |

      operationId: a001-retrieve-service-requests
      responses:
        '200':
          $ref: 'components/schemas/responses/retrieveServiceRequests/200Response.yaml'
        '400':
          $ref: 'components/schemas/responses/retrieveServiceRequests/400Response.yaml'
        '401':
          $ref: 'components/schemas/responses/Unauthorized.yaml'
        '403':
          $ref: 'components/schemas/responses/retrieveServiceRequests/403Response.yaml'
        '406':
          $ref: 'components/schemas/responses/SendNotAcceptable.yaml'
        '429':
          $ref: 'components/schemas/responses/TooManyRequests.yaml'
        '500':
          $ref: 'components/schemas/responses/InternalServerError.yaml'
        '504':
          $ref: 'components/schemas/responses/GatewayTimeout.yaml'
  /FHIR/R4/HealthcareService/{id}:
    get:
      parameters:
        - $ref: 'components/schemas/path/HealthcareId.yaml'
        - $ref: 'components/schemas/headers/request/CorrelationID.yaml'
      operationId: a002-retrieve-healthcare-service
      summary: Retrieve Healthcare Service
      description: | 
        ## Overview

        Use this endpoint to retrieve a specific Healthcare service by their identifier.
      
      responses:
        '200':
          $ref: 'components/schemas/responses/retrieveHealthcareService/200Response.yaml'
        '401':
          $ref: 'components/schemas/responses/Unauthorized.yaml'
        '404':
          $ref: 'components/schemas/responses/retrieveHealthcareService/404Response.yaml'  
        '406':
          $ref: 'components/schemas/responses/SendNotAcceptable.yaml'
        '429':
          $ref: 'components/schemas/responses/TooManyRequests.yaml'
        '500':
          $ref: 'components/schemas/responses/InternalServerError.yaml'
        '504':
          $ref: 'components/schemas/responses/GatewayTimeout.yaml'


          
        


